---
data:
  type: VOC
  train:
    data_roots:
      - /home/junsong_fan/diskf/data/VOC2012/JPEGImages
      - /home/junsong_fan/diskf/data/VOC2012/superpixel/mcg_png
      - ./resources/whats_the_point/train_aug_points_gtBackground_xy.txt
    data_type: [Image, Superpixel, Point]
    image_suffix: [.jpg, .png]
    name_prefix: ./resources/whats_the_point/sets/train_aug.txt
    image_size: [321, 321]
    rand_short: [256, 768]
    rand_crop: true
    rand_mirror: true
    rand_point_shift: 5
    point_size: 20
    max_superpixel: 512
    rtn_image_label: true

  test:
    data_roots:
      - /home/junsong_fan/diskf/data/VOC2012/JPEGImages
      - /home/junsong_fan/diskf/data/VOC2012/extra/SegmentationClassAug
    data_type: [Image, Label2D]
    image_size: ~
    image_suffix: [.jpg, .png]
    name_prefix: ./resources/whats_the_point/sets/val.txt

model:
  type: ProjectionModel
  args:
    base: DeeplabV2_VGG16
    base_args:
      num_classes: 21
      pretrained: ./pretrained/vgg16_20M.pth
    base_stage_names: [c7]
    base_stage_dims: [1024]
    proj_mid_dims: 256
    proj_out_dims: 128
    normalize: true
  params_lr_mult:
    - ['fc8', 10]
    - ['proj', 10]

optimizer:
  type: SGD
  args:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
  scheduler:
    type: Poly
    args:
      num_epochs: 20
      power: 0.9
  batch_size: 16
  num_epochs: 20

test:
  test_epoch_interval: 10
  test_scales: [0.75, 1, 1.25]
  mirror: true

train_func: point_cl_universal

hyperparam:
  use_entropy: false
  superpixel_threshold: 0.3
  tau: 0.07
  warmup: 5
  lambda_superpixel: 1
  lambda_contrastive: 0.1
  proj_type: pix2pix
  limit_pos: 5
  batch_wise: true
  use_memory: false

